use crate::generator::*;

pub fn summary() -> Summary {
    Summary {
        source_folder: "docs",
        categories: vec![
            Category {
                name: "Stack Tutorial".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Introduction",
                        description: "What Stack is and why it exists",
                        folder: "docs/",
                        markdown: include_str!("../content/docs/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Kubernetes Already?",
                        description: "Set up a single-node cluster for local development",
                        folder: "docs/local-kubernetes/",
                        markdown: include_str!("../content/docs/local-kubernetes/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Kubernetes Setup",
                        description: "Install Stack and apply your first StackApp",
                        folder: "docs/kubernetes-setup/",
                        markdown: include_str!("../content/docs/kubernetes-setup/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Database",
                        description: "How CloudNativePG powers Stack databases",
                        folder: "docs/database/",
                        markdown: include_str!("../content/docs/database/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "REST (PostgREST)",
                        description: "Enable PostgREST and query your database over HTTP",
                        folder: "docs/rest/",
                        markdown: include_str!("../content/docs/rest/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Storage",
                        description:
                            "Supabase Storage defaults, MinIO, and how to point at external S3",
                        folder: "docs/storage/",
                        markdown: include_str!("../content/docs/storage/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Realtime",
                        description: "Enable Supabase Realtime and test the endpoint",
                        folder: "docs/realtime/",
                        markdown: include_str!("../content/docs/realtime/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Application Deployment",
                        description: "Configure web services, env vars, and secrets",
                        folder: "docs/app-deploy/",
                        markdown: include_str!("../content/docs/app-deploy/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Authentication",
                        description: "How Stack wires Keycloak and OAuth2 for your apps",
                        folder: "docs/authentication/",
                        markdown: include_str!("../content/docs/authentication/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Ingress",
                        description: "Expose namespaces via Cloudflare tunnels",
                        folder: "docs/ingress/",
                        markdown: include_str!("../content/docs/ingress/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Secrets",
                        description:
                            "Use Kubernetes Secrets with Stack services via env and secret_env",
                        folder: "docs/secrets/",
                        markdown: include_str!("../content/docs/secrets/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Stack Architecture",
                        description: "How the operator, CRDs, and shared services fit together",
                        folder: "docs/architecture/",
                        markdown: include_str!("../content/docs/architecture/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Stack vs Supabase",
                        description: "Compare self-hosted workflows and tradeoffs",
                        folder: "docs/compare/",
                        markdown: include_str!("../content/docs/compare/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Deploy Anywhere".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Hetzner Dedicated Servers",
                        description: "Install k3s on a dedicated box and run multiple StackApps",
                        folder: "docs/deploy-anywhere/hetzner/",
                        markdown: include_str!("../content/docs/deploy-anywhere/hetzner/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "DigitalOcean Droplets",
                        description: "Run k3s on a Droplet and deploy multiple StackApps",
                        folder: "docs/deploy-anywhere/digitalocean/",
                        markdown: include_str!("../content/docs/deploy-anywhere/digitalocean/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Google Compute Engine",
                        description: "Use a single GCE VM for k3s and multiple StackApps",
                        folder: "docs/deploy-anywhere/google/",
                        markdown: include_str!("../content/docs/deploy-anywhere/google/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Frameworks".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Rails on Kubernetes",
                        description: "Containerise a Rails app and ship it with Stack",
                        folder: "docs/framework/",
                        markdown: include_str!("../content/docs/framework/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Flask on Kubernetes",
                        description: "Build a Python/Flask container and deploy it with Stack",
                        folder: "docs/framework/flask/",
                        markdown: include_str!("../content/docs/framework/flask.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Developers".to_string(),
                pages: vec![Page {
                    date: "",
                    title: "Local Workflow",
                    description: "Use k3d and the Justfile recipes to iterate locally",
                    folder: "docs/developers/",
                    markdown: include_str!("../content/docs/developers/index.md"),
                    image: None,
                    author_image: None,
                    author: None,
                }],
            },
        ],
    }
}
