apiVersion: stack-cli.dev/v1
kind: StackApp
metadata:
  name: stack-demo
  namespace: stack-demo
spec:
  components:
    db: {}
    rest: {}
    auth:
      api_external_url: http://localhost:30010/auth
      site_url: http://localhost:30010
      confirm_email: false
    realtime: {}
    storage:
      install_minio: true
      max_upload_size: 50mb
    document_engine: {}
    mailhog: {}
  profiles:
    dev:
      components:
        ingress:
          port: 30010
        db:
          expose_db_port: 30011
          danger_override_password: testpassword
        selenium:
          expose_webdriver_port: 30012
          expose_vnc_port: 30013
        mailhog:
          expose_web_port: 30014
    staging:
      components:
        ingress:
          port: 30090
  services:
    web:
      image: ghcr.io/stack-cli/react-supabase-next:latest
      port: 8080
      env:
        - name: SUPABASE_SERVER_URL
          value: http://nginx
        - name: NEXT_PUBLIC_SUPABASE_URL
          value: http://localhost:30010
      secret_env:
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          secret_name: jwt-auth
          secret_key: anon-jwt
      init:
        image: ghcr.io/stack-cli/react-supabase-next-migrations:latest
        migrations_database_url: MIGRATIONS_URL
