apiVersion: stack-cli.dev/v1
kind: StackApp
metadata:
  name: stack-demo
  namespace: stack-demo
spec:
  components:
    db: {}
    rest: {}
    auth:
      api_external_url: http://localhost:30010/auth
      site_url: http://localhost:30010
      confirm_email: false
    realtime: {}
    storage:
      install_minio: true
    document_engine: {}
    mailhog: {}
  profiles:
    dev:
      components:
        ingress:
          port: 30010
        db:
          expose_db_port: 30011
          danger_override_password: testpassword
        selenium:
          expose_webdriver_port: 30012
          expose_vnc_port: 30013
        mailhog:
          expose_web_port: 30014
    staging:
      components:
        ingress:
          port: 30090
  services:
    web:
      image: mendhak/http-https-echo:latest
      port: 8080
      database_url: DATABASE_URL
      env:
        - name: ECHO_INCLUDE_ENV_VARS
          value: "1"
        - name: JWT_HEADER
          value: Authorization
      init:
        image: alpine:3.18
        env:
          - name: INIT_MESSAGE
            value: "warming up"
