apiVersion: stack-cli.dev/v1
kind: StackApp
metadata:
  name: stack-demo
  namespace: stack-demo
spec:
  components:
    db: {}
    rest: {}
    auth: {}
    realtime: {}
    storage:
      install_minio: true
    document_engine: {}
  profiles:
    dev:
      components:
        ingress:
          port: 30010
        db:
          expose_db_port: 30011
          danger_override_password: testpassword
    staging:
      components:
        ingress:
          port: 30090
  services:
    web:
      image: mendhak/http-https-echo:latest
      port: 8080
      database_url: DATABASE_URL
      env:
        - name: ECHO_INCLUDE_ENV_VARS
          value: "1"
        - name: JWT_HEADER
          value: Authorization
      init:
        image: alpine:3.18
        env:
          - name: INIT_MESSAGE
            value: "warming up"
