apiVersion: stack-cli.dev/v1
kind: StackApp
metadata:
  name: stack-app
  namespace: stack-demo
spec:
  db:
    danger_insecure_password: testpassword
    expose_db_port: 30011
  web:
    image: traefik/whoami:v1.11
    port: 80
    expose_app_port: 30010
  auth:
    jwt: "1"
  storage:
    expose_storage_port: 30012
    install_minio: true
